### ISSUE TITLE
Authentication in PHP

### ISSUE THREAD

**Issue by Arunaliyanaarachchi** [pmill/aws-cognito#1]
Hi, After Days of researching this is the only example i found AWS cognito in PHP.I don't have very broad knowledge of PHP.but still i don't understand how to create the client Object and how can i give my credentials ( not Clear what to provide). can you please help me with that please..?

**Comment by pmill** [comment]
Hello, if you take a look at https://github.com/pmill/aws-cognito/blob/master/examples/bootstrap.php this contains an example of how to create the client and what credentials you need.

**Comment by Arunaliyanaarachchi** [comment]
Yes but wht is this "\pmill\AwsCognito\CognitoClient" instead of this for what i have to refer ..? and what's goes in config file and what is the format ..? can you help ..?

**Comment by pmill** [comment]
`\pmill\AwsCognito\CognitoClient` is the client object you need to create.

You can find an example config here https://github.com/pmill/aws-cognito/blob/master/examples/config.example.php.
