### ISSUE TITLE
User variables must be strings during sign up

### ISSUE THREAD

**Issue by aekarpenko** [pmill/aws-cognito#10]
Signup request throws a serialization exception when ints are passed as user variables. (class com.amazon.coral.value.json.numbers.TruncatingBigNumber can not be converted to an String). Even when the user variable is defined as an int in the Cognito user pool.

Casting (string) before passing to your registerUser function fixes the issue. Perhaps your variables loop can just cast each variable to string? Or is that a bad idea?

**Comment by pmill** [comment]
This has been done in the v0.2.4 release
