### ISSUE TITLE
What to do after access_token expire and there is no refresh token?

### ISSUE THREAD

**Issue by pedjaman** [pmill/aws-cognito#11]
I was using builtin login page. When using response_type=token i don't get refresh token.
When using response_type=code I don't see a way to utilize this class.

So with first approach, after some time, following exception is trigerred (marked with "HERE"):

```php
           try
            {
                $this->client->verifyAccessToken($access_token);
            }
            catch(\pmill\AwsCognito\Exception\TokenExpiryException $e)
            {
// HERE
            }
```
What would be the best approach to handle this case?

Thank you for this class :)

**Comment by claytonpiccinin** [comment]
You can call refreshAuthentication class passing $username and $access_token, it shoult renew and return a new token to be stored.

**Comment by pedjaman** [comment]
Thank you for your response. Unfortunately, that doesn't help. It is throwing an exception.

**Comment by pmill** [comment]
Hi there, do you know what exception is being throw when you call `refreshAuthentication()`?

**Comment by pedjaman** [comment]
Hi :)
unfortunately I cannot recall. Not curently actiove on the project. But it does require refresh_token instead of access_token

**Comment by pmill** [comment]
So the call to `authenticate()` returns an `AuthenticationResultType` object, you should be able to grab the refresh token from that.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AuthenticationResultType.html

**Comment by pedjaman** [comment]
As far as I know from my tests and looking to documentation, there is not refresh_token returned if response_type=token based approach is used. I had to switch using response_type=code based then getting tokens based on code.
But if i get a chance, I will try this above.
