### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by shitalpimpale** [pmill/aws-cognito#16]
For Login API getting below error :

Uncaught exception 'Aws\CognitoIdentityProvider\Exception\CognitoIdentityProviderException' with message 'Error executing "AdminInitiateAuth" on "https://cognito-idp.us-east-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://cognito-idp.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."} UnrecognizedClientException (client): The security token included in the request is invalid. - {"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."}' GuzzleHttp\Exception\ClientException: Client error: `POST https://cognito-idp.us-east-1.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"UnrecognizedClientException","message":"The security token included in the request is invalid."} 

I believe my config setting is correct.

**Comment by bjoernHeneka** [comment]
Hey @shitalpimpale maybe you can post your config here  and add some more information about what you did.

**Comment by pmill** [comment]
@JPOyarzunA I've deleted your comment as it contains your app_client_id and app_client_secret.

**Comment by pmill** [comment]
@shitalpimpale after a google all I can say is ensure that your credentials are correct for the client id and user pool id that you are using.
