### ISSUE TITLE
Change Spomky-Labs/jose to web-token/jwt-framework

### ISSUE THREAD

**Issue by wcoppens** [pmill/aws-cognito#2]
Although updates for Spomky-Labs/jose is guaranteed to end 2018. It is perhaps best to upgrade now that migration shouldn't be difficult.

Migration guide:
https://web-token.spomky-labs.com/migration/spomky-labs-jose/

**Comment by pmill** [comment]
This issue should be resolved now with the v0.2.0 release.

**Comment by aekarpenko** [comment]
web-token/jwt-framework requires PHP 7.1+. Should update readme for this probably as well.
