### ISSUE TITLE
file_get_contents in function downloadJwtWebKeys

### ISSUE THREAD

**Issue by mschmie** [pmill/aws-cognito#27]
I get a timeout when trying to get jwks.json. I think its because of file_get_contents. With curl_exec it does work. Could it be the problem, that I am behind a proxy? Maybe we should than give the possibility to define a proxy maybe via config.php and use it in file_get_contents.

**Comment by pmill** [comment]
Hello

There is a `CognitoClient::setJwtWebKeys()` function where you can download the keys using your own implementation. You should be able to use your curl function in your own code, call `JWKSet::createFromJson($json);` on the response and then set them using this method.
