### ISSUE TITLE
Authenticate method does not handle challenge responses

### ISSUE THREAD

**Issue by wallyholt** [pmill/aws-cognito#3]
Library should handle Cognito challenge responses for things like 'NEW_PASSWORD_REQUIRED', 'SMS_MFA', etc. The 'authenticate' method currently only deals with a positive authentication response, but masks any requests from Cognito for additional information making it look like the authentication failed. 

Details for response types is here: http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminInitiateAuth.html#API_AdminInitiateAuth_ResponseSyntax

I produced the first case by adding a user to my new user pool from the Cognito user pool dashboard and setting a temporary password for the user.

Here is what the response looked like for that case:
<img width="578" alt="screenshot 2017-12-28 19 21 12" src="https://user-images.githubusercontent.com/19600420/34426505-4ec09a76-ec05-11e7-90b4-a7e2bf956606.png">

**Comment by pmill** [comment]
Hello, sorry it'll be at least a few weeks before I can get to this, in the meantime feel free to submit a PR if you know the required code changes.

**Comment by pmill** [comment]
Hello, would you be able to give the code in the master branch a test, the 'authenticate' method should throw a `ChallengeException` now if a challenge response is required. And there is a new 'respondToChallenge' method that should allow you to send the response.

**Comment by engharb** [comment]
Hello @pmill,

I have installed your api via composer two days before and I am wondered that handleAuthenticateResponse() is not in CognitoClient class ?

**Comment by pmill** [comment]
@engharb can you create a new issue for your problem please.

**Comment by pmill** [comment]
This issue should be resolved now with the v0.2.0 release.
