### ISSUE TITLE
Last Api version lacking of handleAuthenticateResponse

### ISSUE THREAD

**Issue by engharb** [pmill/aws-cognito#6]
Hello @pmill,

I have installed your api via composer two days before and I am wondered that handleAuthenticateResponse() is not in CognitoClient class ?

**Comment by pmill** [comment]
Ah, I've not tagged a version that contains those changes yet. If you want to use them in the meantime you can run `composer require pmill/aws-cognito:dev-master`

**Comment by pmill** [comment]
I've tagged a v0.2.0 release that now contains the `handleAuthenticateResponse` method
