### ISSUE TITLE
Convert JWK to public key string PEM/RSAKey

### ISSUE THREAD

**Issue by engharb** [pmill/aws-cognito#7]
Hello, 
Is there a possibility to create public key string .PEM  from JWK. I used before Jose\KeyConverter\RSAKey but I deleted this library because of conflict.?

Any suggestion?

thanks

**Comment by pmill** [comment]
I think the new jwt library has a RSAKey class that might be similar to the one you used.

**Comment by engharb** [comment]
here is such class: Jose\Component\Core\Util\RSAKey
