### ISSUE TITLE
Login Users via Facebook Identity Providers

### ISSUE THREAD

**Issue by engharb** [pmill/aws-cognito#9]
@pmill is there a possibility to login a user using the FB, google account and automatically generate a user account in UserPool? 

I have struggled to find such solution in AWS JS but I could not find any concreted implementation.

regards,

**Comment by pmill** [comment]
It's not something i've looked into for this library, if you find out any information let me know, or if you fancy having a crack at a solution i'd be happy to accept a pull request.

**Comment by engharb** [comment]
@pmill thank you for responding. If i got any thinks related to this problem I will let you know to upgrade with changes.
